service: wengsiong-serverless-nodejs-api
frameworkVersion: '3'

provider: 
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  greeting:
    handler: index.lambdaHandler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
